tools:
  jdk: 8
  maven: 3.5.4

triggers:
- manual: Run default
- manual:
    name: Release Build
    call: release
- manual:
    name: Doc Site Deployment
    call: siteDeploy

flows:
  default:
  - call: versionsCheck
  - call: snapshot

  pr:
  - echo "Running PR build for $GITHUB_PR_URL by ${GITHUB_PR_TRIGGER_SENDER_AUTHOR}"
  - call: versionsCheck
  - call: build

  versionsCheck:
  - (name JDK Version) java -version
  - (name Maven version) mvn -v

  build:
  - (name Maven clean build) mvn -B clean install

  snapshot:
  - exposeVars(maven)
  - (name Project information) echo "Building ${MAVEN_GROUP_ID}:${MAVEN_ARTIFACT_ID}:${MAVEN_VERSION}"
  - (name Maven clean deploy) mvn -B clean deploy

  release:
  - call: versionsCheck
  - exposeVars(maven)
  - var(RELEASE_VERSION = '%{MAVEN_VERSION.replace("-SNAPSHOT", "")}')
  - echo "Starting release process for ${RELEASE_VERSION}"
  - (name Maven release) mvn -B clean release:prepare release:perform

  siteDeploy:
  - exposeVars(maven):
      vars:
        siteurl: 'project/distributionManagement/site/url'
  - (Maven site deploy) mvn -B clean site-deploy
  - echo "Site successfully deployed to ${siteurl}"