tools:
  jdk: 8
  maven: 3.5.2

triggers:
  - manual: Run default
flows:
  default:
    - call: versionsCheck
    - call: pr
  pr:
    - echo "Running build for $GITHUB_PR_URL"
    - call: versionsCheck
    - (name Maven build) mvn clean package

  versionsCheck:
    - (name JDK Version) java -version
    - (name Maven version) mvn -v
